# LatitudeCluster: comece com spec vazio (ou com os campos que o CRD realmente pedir)
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeCluster
metadata:
  name: demo
  namespace: default
spec:
  location: "DAL"
  projectRef:
    projectID: "proj_jv6m5JyZDNLPe"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeMachineTemplate
metadata:
  name: demo-control-plane
  namespace: default
spec:
  template:
    spec:
      projectID: "proj_jv6m5JyZDNLPe"
      site: "DAL"
      plan: "c2.smal.x86"
      operatingSystem: "ubuntu_24_04_x64_lts"
      sshKeys:
      - "ssh_dexA0q4pXalQV"
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: demo-control-plane
  namespace: default
spec:
  replicas: 1
  version: v1.30.0
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: LatitudeMachineTemplate
      name: demo-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager: {}
      scheduler: {}
    initConfiguration: {}
    joinConfiguration: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: demo
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LatitudeCluster
    name: demo
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: demo-control-plane
