# LatitudeCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeCluster
metadata:
  name: capl-demo
  namespace: default
spec:
  location: "SAO2"
  projectRef:
    projectID: "<PROJECT_ID>"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeMachineTemplate
metadata:
  name: capl-demo-control-plane
  namespace: default
spec:
  template:
    spec:
      projectID: "<PROJECT_ID>"
      site: "SAO2"
      plan: "c2.smal.x86"
      operatingSystem: "ubuntu_24_04_x64_lts"
      sshKeys:
      - "<SSH_KEY_ID>"
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: capl-demo-control-plane
  namespace: default
spec:
  replicas: 1
  version: v1.30.0
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: LatitudeMachineTemplate
      name: capl-demo-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      controlPlaneEndpoint: "capl-demo-api.latitude.sh:6443"
      controllerManager: {}
      scheduler: {}
    initConfiguration: {}
    joinConfiguration: {}
---
# Cluster
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capl-demo
  namespace: default
spec:
  controlPlaneEndpoint:
    host: "capl-demo-api.latitude.sh"
    port: 6443
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LatitudeCluster
    name: capl-demo
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: capl-demo-control-plane
