apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: LatitudeMachine
metadata:
  name: example-latitudemachine
  namespace: default
spec:
  projectID: "<PROJECT_ID>"
  site: "SAO2"
  plan: "c2-small-x86"
  operatingSystem: "ubuntu_24_04_x64_lts"
  sshKeys: ["<SSH_KEY_ID>"]
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfig
metadata:
  name: example-kubeadmconfig
  namespace: default
spec:
  joinConfiguration:
    nodeRegistration:
      name: "{{ ds.meta_data.hostname }}"
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Machine
metadata:
  name: example-machine
  namespace: default
spec:
  clusterName: capl-demo
  version: v1.30.0
  bootstrap:
    configRef:
      apiGroup: bootstrap.cluster.x-k8s.io
      kind: KubeadmConfig
      name: example-kubeadmconfig
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: LatitudeMachine
    name: example-latitudemachine
