---
# Complete RKE2 Cluster Example with SSH Keys from Kubernetes Secret
# This example demonstrates the new SSH key configuration using Kubernetes Secrets
#
# Prerequisites:
# 1. kubectl configured with your management cluster
# 2. CAPL installed on the management cluster
# 3. Latitude.sh API credentials configured
# 4. SSH keys secret created (see step 1 below)
#
# Setup:
# 1. Create the SSH keys secret first (choose one method):
#
#    Method A - Manual secret (development/testing):
#      kubectl create secret generic latitude-ssh-keys \
#        --from-literal=ssh-key-ids="ssh_abc123,ssh_def456" \
#        --namespace default
#
# 2. Update the PROJECT_ID, location, and cluster name in this file
# 3. Apply: kubectl apply -f rke2-cluster-with-secrets.yaml

---
# Cluster Definition

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.244.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
  controlPlaneEndpoint:
    host: capi-endpoint  # CHANGE THIS: Your DNS name for control plane
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: my-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LatitudeCluster
    name: my-cluster

---
# Latitude Infrastructure

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  location: "SAO2"  # CHANGE THIS: Your preferred Latitude.sh location
  projectRef:
    projectID: "<PROJECT_ID>"  # CHANGE THIS: Your Latitude.sh project ID

---
# Control Plane Machine Template (using secret reference)

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeMachineTemplate
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      plan: "c2-small-x86"  # CHANGE THIS: Your preferred plan
      operatingSystem: "ubuntu_24_04_x64_lts"
      # Reference the SSH keys secret created above
      sshKeySecretRef:
        name: latitude-ssh-keys
        namespace: default

---
# RKE2 Control Plane Configuration

apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  replicas: 1
  version: v1.30.0+rke2r1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LatitudeMachineTemplate
    name: my-cluster-control-plane
  agentConfig:
    nodeName: '{{ ds.meta_data.hostname }}'
  serverConfig:
    cni: calico
    tlsSan:
      - capi-endpoint  # CHANGE THIS: Your DNS name
      - 127.0.0.1
  registrationMethod: internal-first
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  preRKE2Commands:
    - ufw --force enable
    - ufw default deny incoming
    - ufw default allow outgoing
    - ufw allow 22/tcp
    - ufw allow 6443/tcp
    - ufw allow 9345/tcp
    - ufw allow 2379:2380/tcp
    - ufw allow 10250/tcp
    - ufw allow 4789/udp
    - ufw --force enable

---
# Worker Node Machine Template (using secret reference)

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeMachineTemplate
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      plan: "c2-small-x86"  # CHANGE THIS: Your preferred plan
      operatingSystem: "ubuntu_24_04_x64_lts"
      # Reference the same SSH keys secret
      sshKeySecretRef:
        name: latitude-ssh-keys
        namespace: default

---
# Worker Node Bootstrap Configuration

apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      agentConfig:
        nodeName: '{{ ds.meta_data.hostname }}'
      preRKE2Commands:
        - ufw --force enable
        - ufw default deny incoming
        - ufw default allow outgoing
        - ufw allow 22/tcp
        - ufw allow 10250/tcp
        - ufw allow 4789/udp
        - ufw allow 30000:32767/tcp
        - ufw --force enable

---
# Worker Node Deployment

apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  clusterName: my-cluster
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/deployment-name: my-cluster-md-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/deployment-name: my-cluster-md-0
        cluster.x-k8s.io/cluster-name: my-cluster
    spec:
      clusterName: my-cluster
      version: v1.30.0+rke2r1
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: RKE2ConfigTemplate
          name: my-cluster-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: LatitudeMachineTemplate
        name: my-cluster-md-0
