---
# High Availability RKE2 Cluster with VLAN + MetalLB
# This example demonstrates:
# - 3-node HA control plane with automatic providerID configuration
# - VLAN networking for private node communication (using vlanConfig)
# - MetalLB for LoadBalancer services without CCM
# - Dynamic node-ip configuration from VLAN interface
#
# Prerequisites:
# 1. Create SSH keys secret: kubectl create secret generic latitude-ssh-keys --from-literal=authorized_keys="ssh-rsa ..."
# 2. Update project ID, location, and control plane endpoint
# 3. Configure vlanConfig with your VLAN subnet (controller will manage VLAN)
#
# The controller will:
# - Create/manage VLAN based on vlanConfig
# - Assign VLAN IPs to servers automatically

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vlan-ha-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.244.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
  controlPlaneEndpoint:
    host: "your-cluster-endpoint.example.com"  # Update with your DNS or VIP
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: vlan-ha-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LatitudeCluster
    name: vlan-ha-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeCluster
metadata:
  name: vlan-ha-cluster
  namespace: default
spec:
  location: "SAO2"
  projectRef:
    projectID: "proj_xxxxx"  # Update with your project ID
  # VLAN configuration - controller will create and manage VLAN
  vlanConfig:
    subnet: "10.20.0.0/24"  # VLAN subnet for private node communication
    # vid: 2011             # Optional: specific VLAN ID (auto-assigned if not specified)
    # existingVLANID: "vlan_xxx"  # Optional: use existing VLAN instead of creating
    # networkInterface: "eno2"    # Optional: network interface (auto-detected if not specified)
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: LatitudeMachineTemplate
metadata:
  name: vlan-ha-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      plan: "c2-small-x86"
      operatingSystem: "ubuntu_24_04_x64_lts"
      sshKeySecretRef:
        name: latitude-ssh-keys
        namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: vlan-ha-cluster-control-plane
  namespace: default
spec:
  replicas: 3
  version: v1.30.0+rke2r1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: LatitudeMachineTemplate
    name: vlan-ha-cluster-control-plane
  agentConfig:
    nodeName: '{{ ds.meta_data.hostname }}'
  serverConfig:
    cni: calico
    tlsSan:
      - your-cluster-endpoint.example.com  # Update to match controlPlaneEndpoint
      - 127.0.0.1
      - localhost
  registrationMethod: internal-first
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  files:
    # Script to detect VLAN interface and configure networking
    # The VLAN IP is assigned by the Latitude controller via the API
    - path: /usr/local/bin/configure-vlan-ip.sh
      owner: root:root
      permissions: "0755"
      content: |-
        #!/bin/bash
        set -e

        # Find VLAN interface (format: vlan.XXXX or vlanXXXX)
        VLAN_IFACE=$(ip link show | grep -oP 'vlan\.\d+|vlan\d+' | head -1)

        if [ -z "$VLAN_IFACE" ]; then
          echo "No VLAN interface found, checking for tagged interfaces..."
          # Try to find interface with VLAN tag
          VLAN_IFACE=$(ip -d link show | grep -B1 'vlan protocol' | grep -oP '^\d+: \K[^@:]+' | head -1)
        fi

        if [ -z "$VLAN_IFACE" ]; then
          echo "WARNING: No VLAN interface detected"
          exit 0
        fi

        echo "Found VLAN interface: $VLAN_IFACE"

        # Get the IP from the VLAN interface
        VLAN_IP=$(ip -4 addr show "$VLAN_IFACE" 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)

        if [ -n "$VLAN_IP" ]; then
          echo "VLAN IP: $VLAN_IP"
          echo "$VLAN_IP" > /etc/latitude-vlan-ip

          # Configure RKE2 to use VLAN IP for node-ip
          mkdir -p /etc/rancher/rke2/config.yaml.d
          cat > /etc/rancher/rke2/config.yaml.d/50-node-ip.yaml <<'NODEIP'
        node-ip: $VLAN_IP
        NODEIP
          sed -i "s/\$VLAN_IP/$VLAN_IP/" /etc/rancher/rke2/config.yaml.d/50-node-ip.yaml
          echo "Configured RKE2 node-ip: $VLAN_IP"
        else
          echo "WARNING: VLAN interface found but no IP assigned yet"
        fi

    # Script to query Latitude API and get server ID for providerID
    - path: /usr/local/bin/get-latitude-server-id.sh
      owner: root:root
      permissions: "0755"
      content: |-
        #!/bin/bash
        # Get server ID from Latitude API using hostname or public IP

        API_KEY="${LATITUDE_API_KEY:-}"
        PROJECT_ID="${LATITUDE_PROJECT_ID:-}"

        if [ -z "$API_KEY" ] || [ -z "$PROJECT_ID" ]; then
          echo "ERROR: LATITUDE_API_KEY and LATITUDE_PROJECT_ID must be set" >&2
          exit 1
        fi

        PUBLIC_IP=$(curl -s --connect-timeout 5 ifconfig.me || hostname -I | awk '{print $1}')
        HOSTNAME=$(hostname)

        # Query Latitude API
        RESPONSE=$(curl -s --connect-timeout 10 \
          -H "Authorization: Bearer $API_KEY" \
          "https://api.latitude.sh/servers?filter[project]=$PROJECT_ID")

        # Try to find server by IP
        SERVER_ID=$(echo "$RESPONSE" | python3 -c "
        import sys, json
        data = json.load(sys.stdin)
        target_ip = '$PUBLIC_IP'
        target_hostname = '$HOSTNAME'
        for server in data.get('data', []):
            attrs = server.get('attributes', {})
            if attrs.get('primary_ipv4') == target_ip:
                print(server['id'])
                sys.exit(0)
        for server in data.get('data', []):
            attrs = server.get('attributes', {})
            if attrs.get('hostname') == target_hostname:
                print(server['id'])
                sys.exit(0)
        sys.exit(1)
        " 2>/dev/null)

        if [ -n "$SERVER_ID" ]; then
          echo "$SERVER_ID"
        else
          exit 1
        fi

    # Store Latitude credentials for providerID lookup
    - path: /etc/latitude-credentials
      owner: root:root
      permissions: "0600"
      content: |-
        LATITUDE_API_KEY=your_api_key_here
        LATITUDE_PROJECT_ID=proj_xxxxx

  preRKE2Commands:
    # Configure firewall
    - ufw --force enable
    - ufw default deny incoming
    - ufw default allow outgoing
    - ufw allow 22/tcp
    - ufw allow 6443/tcp
    - ufw allow 9345/tcp
    - ufw allow 2379:2380/tcp
    - ufw allow 10250/tcp
    - ufw allow 10259/tcp
    - ufw allow 10257/tcp
    - ufw allow 4789/udp
    - ufw allow 5473/tcp comment 'Calico Typha'
    - ufw --force enable

    # Configure kernel modules and networking
    - modprobe overlay
    - modprobe br_netfilter
    - sysctl -w net.bridge.bridge-nf-call-iptables=1
    - sysctl -w net.ipv4.ip_forward=1
    - swapoff -a

    # Wait for VLAN to be configured by Latitude (IP assigned via API)
    - echo "=== Waiting for VLAN configuration ==="
    - |
      for i in $(seq 1 30); do
        VLAN_IFACE=$(ip link show 2>/dev/null | grep -oP 'vlan\.\d+|vlan\d+' | head -1)
        if [ -n "$VLAN_IFACE" ]; then
          VLAN_IP=$(ip -4 addr show "$VLAN_IFACE" 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
          if [ -n "$VLAN_IP" ]; then
            echo "VLAN interface $VLAN_IFACE ready with IP: $VLAN_IP"
            break
          fi
        fi
        echo "Waiting for VLAN IP assignment... ($i/30)"
        sleep 10
      done

    # Configure VLAN IP for RKE2
    - /usr/local/bin/configure-vlan-ip.sh

    # Configure Latitude providerID
    - echo "=== Configuring Latitude providerID ==="
    - |
      source /etc/latitude-credentials
      export LATITUDE_API_KEY LATITUDE_PROJECT_ID
      SERVER_ID=$(/usr/local/bin/get-latitude-server-id.sh 2>/dev/null || echo "")
      if [ -z "$SERVER_ID" ]; then
        echo "WARNING: Could not determine server ID, providerID will not be set"
      else
        echo "Found server ID: $SERVER_ID"
        mkdir -p /etc/rancher/rke2/config.yaml.d
        echo "kubelet-arg:" > /etc/rancher/rke2/config.yaml.d/99-provider-id.yaml
        echo "  - \"provider-id=latitude://$SERVER_ID\"" >> /etc/rancher/rke2/config.yaml.d/99-provider-id.yaml
        echo "Configured providerID: latitude://$SERVER_ID"
      fi

  postRKE2Commands:
    - export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
    - sleep 30
    - echo "=== Installing MetalLB ==="
    - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
    - echo "=== Waiting for MetalLB to be ready ==="
    - kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=120s || echo "MetalLB not ready yet"
    - echo "=== Node Status ==="
    - kubectl get nodes -o wide
    - echo "=== ProviderID Status ==="
    - kubectl get nodes -o custom-columns=NAME:.metadata.name,PROVIDERID:.spec.providerID
    - echo "=== Control plane ready ==="
    - echo "MetalLB installed - apply IPAddressPool and L2Advertisement to complete"
